Add support for old version of MacVim in CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,23 +25,38 @@ anchors:
       - docker run --rm -it -v "${PWD}:/root" -v "${HOME}/cache/themis-${THEMIS_VERSION}:/tmp/themis" --entrypoint /tmp/themis/bin/themis "thinca/vim:${VIM_VERSION}" --reporter dot
   osx: &osx
     os: osx
-    cache:
-      directories:
-        - *cache_dir
-        - $HOME/Library/Caches/Homebrew
-        - /usr/local/Homebrew/Library/Homebrew/vendor/
-        - /usr/local/Homebrew/Library/Taps/
-    addons:
-      homebrew:
-        packages:
-          - macvim
-        update: true
-    before_cache:
-      - brew cleanup
     install:
-      - ln -fs "$(brew --prefix macvim)/bin/mvim" "/usr/local/bin/vim"
+      - |
+        if [[ ${VIM_VERSION} = 'latest' ]]; then
+          VIM_URL=$(curl -s --retry 3 'https://vim-jp.org/redirects/macvim-dev/macvim/latest.json' | sed 's@.*"redirect_url":"\([^"]*\)".*@\1@')
+          if [[ -z "${VIM_URL}" ]]; then
+            echo "Can't get Vim's URL" >&2
+            exit 64
+          fi
+          VIM_VERSION=$(echo ${VIM_URL} | sed 's@.*/download/\([^/]*\).*@\1@')
+          if [[ -z "${VIM_VERSION}" ]]; then
+            echo "Can't detect Vim's version from URL(${VIM_URL})" >&2
+            exit 65
+          fi
+        fi
+      - |
+        if [[ ! -d "${HOME}/cache/macvim-${VIM_VERSION}" ]]; then
+          echo "Download from ${VIM_URL}"
+          curl --silent --location --output "/tmp/MacVim.dmg" "${VIM_URL}"
+          hdiutil attach -quiet -mountpoint "/Volumes/MacVim" "/tmp/MacVim.dmg"
+          mkdir -p "${HOME}/cache/macvim-${VIM_VERSION}"
+          cp -r "/Volumes/MacVim/MacVim.app" "${HOME}/cache/macvim-${VIM_VERSION}"
+          hdiutil detach "/Volumes/MacVim"
+          rm "/tmp/MacVim.dmg"
+        fi
+      - |
+        if [[ -x ""${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/bin/vim"" ]]; then
+          export THEMIS_VIM="${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/bin/vim"
+        elif [[ -x ""${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/MacOS/Vim"" ]]; then
+          export THEMIS_VIM="${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/MacOS/Vim"
+        fi
     script:
-      - ${THEMIS_VIM:-vim} --version
+      - ${THEMIS_VIM} --version
       - ${HOME}/cache/themis-${THEMIS_VERSION}/bin/themis --reporter dot
   windows: &windows
     os: windows
@@ -76,7 +91,7 @@ anchors:
         fi
       - export THEMIS_VIM=$(echo ${HOME}/cache/vim-${VIM_VERSION}/vim/*/vim.exe)
     script:
-      - ${THEMIS_VIM:-vim} --version
+      - ${THEMIS_VIM} --version
       - ${HOME}/cache/themis-${THEMIS_VERSION}/bin/themis.bat --reporter dot
 
 jobs:
@@ -90,6 +105,19 @@ jobs:
     - <<: *linux
       env: VIM_VERSION=latest
     - <<: *osx
+      env:
+        - VIM_VERSION=v7.4.903
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-79/MacVim-7.4.dmg
+    - <<: *osx
+      env:
+        - VIM_VERSION=v8.0.0003
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-110/MacVim.dmg
+    - <<: *osx
+      env:
+        - VIM_VERSION=v8.1.0039
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-148/MacVim.dmg
+    - <<: *osx
+      env: VIM_VERSION=latest
     - <<: *windows
       env: VIM_VERSION=v7.3
     - <<: *windows
